# Generated by Django 5.0.6 on 2024-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pm25',
        ),
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=50),
        ),
    ]
